global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'rag-api-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'fastapi'
    static_configs:
      - targets: ['api:8000']
    scrape_interval: 5s
    metrics_path: '/metrics'

  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    scrape_interval: 30s
