apiVersion: v1
kind: Service
metadata:
  name: school-rag-ui
  namespace: school-rag
  labels:
    app: school-rag-ui
spec:
  type: NodePort
  selector:
    app: school-rag-ui
  ports:
    - name: http
      port: 8501
      targetPort: 8501
      nodePort: 30085
